name: Package exe with PyInstaller - Windows

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: build.spec

    - run: mv dist/windows/DeleteMyHistory.exe DeleteMyHistory.exe

    - uses: actions/upload-artifact@v4
      with:
        name: DeleteMyHistory
        path: |
          DeleteMyHistory.exe
          config.toml
          cookie.txt

    - run: "${{ format('zip -r delete-my-history-in-tieba-{0}.zip DeleteMyHistory.exe config.toml cookie.txt', github.ref_name) }}"

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: delete-my-history-in-tieba-*.zip
